# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv:
  - .env

tasks:
  build: web-ext build -s src/ -a out/ -o
  validate: web-ext lint -s src/
  run: web-ext run -s src/ -t firefox-android --adb-device $ADB_DEVICE --firefox-apk $FIREFOX_APK
