# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv:
  - .env

tasks:
  build:
    desc: Builds the extension
    cmd: web-ext build -s src/ -a out/ -o

  validate:
    desc: Validates the extension
    cmd: web-ext lint -s src/

  run:
    desc: Runs the extension
    cmd: web-ext run -s src/ -t firefox-android --adb-device $ADB_DEVICE --firefox-apk $FIREFOX_APK

  format:
    desc: Formats the code
    cmd: biome format --write .

  lint:
    desc: Lints the code
    cmd: biome check .

  check:
    desc: Formats and lints the code
    cmd: task format lint
