# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

silent: true

dotenv:
  - .env

tasks:
  build:
    cmd: web-ext build -s src/ -a out/ -o

  validate:
    cmd: web-ext lint -s src/

  generate:
    cmd: bash scripts/gen-script.sh

  run:
    cmd: web-ext run -s src/ -t firefox-android --adb-device $ADB_DEVICE --firefox-apk $FIREFOX_APK

  format:
    cmd: biome format --write .

  lint:
    cmd: biome check .

  check:
    cmd: task format lint
